### ISSUE TITLE
use_color_mode resets the value in local storage to auto, when reloading the page

### ISSUE THREAD

**Issue by SeraphyBR** [Synphonyte/leptos-use#100]
I don't know if this is intentional, but I intended to use use_color_mode() to implement a dark mode toggle button on my website, but I noticed that when I reloaded it went back to "auto", which contradicts the idea of persisting. A clear example is in the documentation itself, it is possible to see this behavior.

**Comment by SeraphyBR** [comment]
https://leptos-use.rs/browser/use_color_mode.html Just click the button to change the theme, and reload the page

**Comment by maccesch** [comment]
You are right! I can reproduce. Thanks for reporting, I'll fix it ASAP!
