### ISSUE TITLE
Demo for `use_cookie` in the book is misaligned

### ISSUE THREAD

**Issue by maccesch** [Synphonyte/leptos-use#102]
Just habe a look at the book and you see what I mean :D

**Comment by hcandelaria** [comment]
Can I give this a try?

Just to confirm, the changes needed are:

Updating the first paragraph to correct grammatical errors.
Modifying the usage example to include counter_a and counter_b.

Am I on the right track?

**Comment by maccesch** [comment]
This would be great!

If there are grammatical errors please always feel free to correct them. I'm not a native speaker.

But I'm talking about the layout as shown below.

<img width="483" alt="Screenshot 2024-07-16 at 11 10 07" src="https://github.com/user-attachments/assets/0dda662e-4746-4ebd-acf6-b33d0476d2cc">

**Comment by maccesch** [comment]
Awesome, thanks! I didn't provide any good description, so no worries. 👍🏼👍🏼
