### ISSUE TITLE
Using `leptos_use` with fermyon spin

### ISSUE THREAD

**Issue by anvlkv** [Synphonyte/leptos-use#104]
Hi, I just tried new (`0.10.10`) version with fermyon `spin` (it is a `wasm32-wasi` target) and it appears it would still call some `js-sys` even with `wasm_ssr` feature causing an error.  I'm using `use_local_storage`. 

Is that the intention to be able to use `wasm_ssr` instead of `ssr` for a `wasm32-wasi` target? 

It works fine on `0.10.9` with `ssr` feature

**Comment by maccesch** [comment]
I didn't change anything exept adding the warning in a build script. So it is very very unlikely that sth broke. Did you remove the `ssr` feature? You config is supposed to stay unchanged. Only add the `wasm_ssr` feature on top to get rid of the warning. Please check the docs

**Comment by anvlkv** [comment]
Thanks! Sorry for disturbance
