### ISSUE TITLE
Add heart beat option to use_websocket

### ISSUE THREAD

**Issue by maccesch** [Synphonyte/leptos-use#116]
As mentioned in #115 

Should be opt-in.

**Comment by johansmitsnl** [comment]
@maccesch With the latest commit you also need to enable the `use_interval_fn` feature. If not you will get a compilation error:

```
   Compiling leptos-use v0.14.0 (https://github.com/Synphonyte/leptos-use.git?branch=main#85fcf135)
error[E0432]: unresolved import `crate::use_interval_fn`
  --> /home/user/.cargo/git/checkouts/leptos-use-1f72e309245d77d4/85fcf13/src/use_websocket.rs:3:41
   |
3  | use crate::{core::ConnectionReadyState, use_interval_fn, ReconnectLimit};
   |                                         ^^^^^^^^^^^^^^^ no `use_interval_fn` in the root
   |
note: found an item that was configured out
  --> /home/user/.cargo/git/checkouts/leptos-use-1f72e309245d77d4/85fcf13/src/lib.rs:94:5
   |
94 | mod use_interval_fn;
   |     ^^^^^^^^^^^^^^^
note: the item is gated behind the `use_interval_fn` feature
  --> /home/user/.cargo/git/checkouts/leptos-use-1f72e309245d77d4/85fcf13/src/lib.rs:93:7
   |
93 | #[cfg(feature = "use_interval_fn")]
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The `use_websocket` feature should also enable the `use_interval_fn` feature.

**Comment by maccesch** [comment]
Oh, yes!! Fixing right now. There will be a new release soon.

**Comment by johan-smits** [comment]
While testing the new feature I noticed that in the documentation you create a [Display](https://github.com/Synphonyte/leptos-use/blob/52fb2b6981b8ba01f82bc969ed88b936c115c915/src/use_websocket.rs#L129-L133) implementation. But in the code it uses the [Default](https://github.com/Synphonyte/leptos-use/blob/52fb2b6981b8ba01f82bc969ed88b936c115c915/src/use_websocket.rs#L404C38-L404C40). When I use the default it works fine.

**Comment by maccesch** [comment]
The `Display` is the recommended way to implement `ToString`. This is needed for the `FromToStringCodec` to work.
