### ISSUE TITLE
[Bug] on_click_outside lint message appears even though it (probably) shouldn't

### ISSUE THREAD

**Issue by SleeplessOne1917** [Synphonyte/leptos-use#118]
I'm using `on_click_outside` in my codebase and am getting this lint warning:

```
unused implementer of `FnOnce` that must be used
closures are lazy and do nothing unless called
```

Here is the relevant snippet of code it's complaining about:

```rust
  let dropdown_node_ref = NodeRef::<Details>::new(); // This gets used in code not included here
  on_click_outside(dropdown_node_ref, move |_| {
    // Using this approach instead of conditional rendering so that the dropdown works at least somewhat when JS is disabled
    if let Some(el) = dropdown_node_ref.get() {
      let _ = el.attr("open", None::<&str>);
    }
  });
```

Is this a problem with how I'm using the function, or is this an issue in the library?

**Comment by maccesch** [comment]
`on_click_outside` returns a closure that you can call to stop the behavior. So to get rid of this warning you can simply do

```rust
let _ = on_click_outside(...)
```

**Comment by SleeplessOne1917** [comment]
Ah, my bad. Thank you for your prompt response.

**Comment by maccesch** [comment]
It's not documented, so guess my bad 😂

**Comment by maccesch** [comment]
To "unlisten" everything
