### ISSUE TITLE
Add mediaDevices.getUserMedia 

### ISSUE THREAD

**Issue by hcandelaria** [Synphonyte/leptos-use#128]
the mediaDevices.getUserMedia is similar to getDisplayMedia. I tried experimenting with this using the `user_display_media` as a starting point and it looks to be working for me.

I can submit a PR, but I would need guidance on the new function template and running the tests.

**Comment by maccesch** [comment]
That sounds great!

Just follow this https://github.com/synphonyte/leptos-use?tab=readme-ov-file#new-function-template and all the necessary files will be generated for you. You can then paste your code that you already wrote. You might have to rename you current file first so the template doesnt have any conflicts.

To run tests:

```shell
cargo test --features math,docs,ssr
```
