### ISSUE TITLE
`use_locale` doesn't implements language negotiation

### ISSUE THREAD

**Issue by mondeja** [Synphonyte/leptos-use#144]
Take into acount the next cases:

### [ISO 639-1 codes](https://wikipedia.org/wiki/ISO_639-1)

- Supported locales are `["en", "de"]`.
- The user has the browser locales `["en-MP", "en-US", "en"]`.

The signal created by `use_locale` will return `"en-MP"`, which is not really supported.

### [ISO 639-3 codes](https://en.wikipedia.org/wiki/ISO_639-3)

The problem becomes worse if we take into account ISO 639-3 codes.

- Supported locales are `["en", "ka"]`.
- The user has the browser locales `["kam-KE", "en"]`.

The signal created by `use_locale` will return `"kam-KE"`, which is not even supported.

> - `ka` is Georgian
> - `kam` is the [Kamba language](https://en.wikipedia.org/wiki/Kamba_language)

### Solution

That's why i18n programs usually implement language negotiation.

- See [`LanguageIdentifier::matches`](https://docs.rs/unic-langid/latest/unic_langid/struct.LanguageIdentifier.html#method.matches) on [`unic_langid`](https://docs.rs/unic-langid).
- See this function in leptos-fluent as example: https://github.com/mondeja/leptos-fluent/blob/66655441c3ae5a99400f5a6fc41ba00117e2add2/leptos-fluent/src/lib.rs#L717-L788

**Comment by maccesch** [comment]
Thanks for pointing me in the right direction here!
