### ISSUE TITLE
use_cookie example not reproducible

### ISSUE THREAD

**Issue by JosiahParry** [Synphonyte/leptos-use#150]
The use_cookie references a trait `FromToStringCodec` this is not hyperlinked in the docs: https://docs.rs/leptos-use/latest/leptos_use/fn.use_cookie.html

below the example code it references ["the codec chapter"](https://leptos-use.rs/codecs.html).

From there, it looks like there is an issue rendering the docs book

<img width="357" alt="image" src="https://github.com/user-attachments/assets/88b978a1-b274-4937-8a65-1dafb0057f92">

the link for `FromToStringCodec` is broken: https://github.com/Synphonyte/leptos-use/blob/main/src/utils/codecs/string/from_to_string.rs

It would be great if the documentation for this handy function provided a reproducible example. As it stands, there is no clear way to use this function—which is a bummer because it looks so useful!

**Comment by maccesch** [comment]
We recently moved all the codecs into its own crate called `codee`. Leptos 0.7 resources now use that crate as well.

I guess we forgot to update the chapter in the book. Sorry about that!

**Comment by JosiahParry** [comment]
Gocha! So including `codee` to Cargo.toml is the way forward, ya?

**Comment by maccesch** [comment]
You can find the corrected chapter now here: https://github.com/Synphonyte/leptos-use/blob/main/docs/book/src/codecs.md
