### ISSUE TITLE
When using the leptos-use with feature 'ssr', the compilation cannot be passed.

### ISSUE THREAD

**Issue by tqq1994516** [Synphonyte/leptos-use#175]
For more details, you can take a look at this issue.https://github.com/fermyon/leptos-spin/issues/45

**Comment by maccesch** [comment]
could you create a PR for this, please?

**Comment by tqq1994516** [comment]
> could you create a PR for this, please?

OK. I will create a PR later.

**Comment by tqq1994516** [comment]
> could you create a PR for this, please?

done
