### ISSUE TITLE
make `use_storage` remove the key when `reset` is called

### ISSUE THREAD

**Issue by maccesch** [Synphonyte/leptos-use#180]

**Comment by maccesch** [comment]
Did you test it in the browser?

**Comment by flaviopezzini** [comment]
Didn't, just wanted to confirm as the code seem to be already implemented. Cool stuff, I'll try this out later and see if I can figure it out.

**Comment by flaviopezzini** [comment]
I was able to replicate the issue on Brave. On Firefox however, it works as expected. 
I have also noticed that the automatic refresh of the storage when the user types something on the text fields is a bit flaky, not sure yet if that's the storage API or the code listening to input events on the text fields.
My hunch is that something is getting lost in the translation to wasm.
I'll carry on my debugging next week.

**Comment by maccesch** [comment]
Sounds good. Thanks!

**Comment by flaviopezzini** [comment]
https://github.com/Synphonyte/leptos-use/pull/206 Raised.
