### ISSUE TITLE
Support IndexedDb storage

### ISSUE THREAD

**Issue by gitmalong** [Synphonyte/leptos-use#25]
Not sure if this is in scope of the project but calling indexeddb without much boilerplate would be nice :)

**Comment by maccesch** [comment]
I think it's in scope. We already have `use_storage` so this seems a natural progression. Thanks for the suggestion!

Do you have any ideas about the API you'd like to see or what you think would be important to know to design an API?

**Comment by gitmalong** [comment]
So what I found is https://crates.io/crates/indexed_db_futures but when thinking over this topic I would love to see a database such as https://duckdb.org/ or https://github.com/gluesql/gluesql more. Gluesql abstracts over storage types and does also support IndexedDb. I can imagine it be easier to integrate.

**Comment by maccesch** [comment]
Thanks for the research! It seems to me that GlueSQL already handles all of this. I didn't know it at all but it seems pretty nice!

What additional benefit would you wish for on top of that?

**Comment by gitmalong** [comment]
> Thanks for the research! It seems to me that GlueSQL already handles all of this. I didn't know it at all but it seems pretty nice!

That's the question - haha. I am currently playing around and right now I am not sure whether anything on top is even needed. I am fetching data via Leptos `create_local_resource` and this works fine so far.

**Comment by maccesch** [comment]
Cool! Let me know if you find sth that would make integrating it with leptos nicer. 

Closing this for now. Feel free to re-open.
