### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by MrChaker** [Synphonyte/leptos-use#26]
After I add the library ( tried it twice ) , when I run cargo leptos watch I get this error 

thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:9:
cannot call wasm-bindgen imported functions on non-wasm targets
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
hread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_axum-0.4.10/src/lib.rs:1042:14:
  called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(2), ...)

**Comment by maccesch** [comment]
That usually means, that you didn't pass the feature `ssr` to leptos-use when using it in a server context.

Please see https://leptos-use.rs/server_side_rendering.html for how to do that

**Comment by MrChaker** [comment]
> 

I added it , the error still occurs

**Comment by maccesch** [comment]
Then without more information I don't know what to do here. This error occurs when you try to call some wasm stuff from within the server. What part of the code is causing this issue?

**Comment by MrChaker** [comment]
Do you know what's the diffirence between ssr and hydrate .
leptos-use doesn't have hydrate feature ?

**Comment by maccesch** [comment]
It seems to me you need to read the leptos docs first on this topic. leptos-use indeed doesn't have a hydrate feature.
