### ISSUE TITLE
Consider individual feature-gates for functions

### ISSUE THREAD

**Issue by lpotthast** [Synphonyte/leptos-use#3]
It should be profiled if adding features for all functions (possibly with the same name as the function) reduces wasm binary size when an application or library depending on leptos-use only reqiures a limited set of features from it.

A feature named "full" could be added, automatically enabling all functionality of leptos-use to still enable easy usage if needed.

**Comment by maccesch** [comment]
That’s a very good question. I remember reading sth that when you turn on certain optimizations the rust compiler will get rid of unused code automatically. 

But you’re right we should try and see if that’s the case!

**Comment by lpotthast** [comment]
Sound great 👍🏻
