### ISSUE TITLE
use Window as el in use_scroll

### ISSUE THREAD

**Issue by MrChaker** [Synphonyte/leptos-use#31]
use_scroll take an el param , why can't we pass window() to it , any workaround for this ?

**Comment by maccesch** [comment]
Yep! I'm actually working on this right now 👍🏼

**Comment by maccesch** [comment]
Oh I might actually have misunderstood this issue. You can use [`use_window_scroll`]() instead. Does that help?

**Comment by MrChaker** [comment]
> Oh I might actually have misunderstood this issue. You can use `use_window_scroll` instead. Does that help?

I don't think so , As I need also a writeSignal ( set_x / set_y ).

**Comment by maccesch** [comment]
I see. Checking...

**Comment by MrChaker** [comment]
For now I'm using this  window().scroll_with_scroll_to_options , but for some reason it doesn't work on mobile

**Comment by maccesch** [comment]
you can try sth like this:

```rust
let UseScrollReturn { ... } = use_scroll("html");
```

**Comment by MrChaker** [comment]
Thank you .
I've found a solution to my problem ( not related to use_scroll ) .
Generaly, window.scroll() doesn't work on mobile browsers by default , unless you add this meta tag
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1" />

**Comment by maccesch** [comment]
I see. Good to know!
