### ISSUE TITLE
Add the missing field `vibrate` to `UseWebNotificationOptions`

### ISSUE THREAD

**Issue by maccesch** [Synphonyte/leptos-use#40]
Once the next version **web_sys version 0.3.65** releases:

Add the following fields to `UseWebNotificationOptions` and `ShowOptions`:
- [x] `renotify`
- [x] `vibrate`  
- [x] `silent`
- [x] `image`

**Comment by hcandelaria** [comment]
PR #142 should help with this. Let me know if you have any feedback.
I don't think we can add `vibrate` just yet, I didn't see it in web_sys::NotificationOptions.

**Comment by maccesch** [comment]
We might have to open a PR on web_sys for this.

**Comment by hcandelaria** [comment]
I'm working on adding the `vibrate` feature, but I'm encountering some difficulties with testing. I intended to test it on a compatible device, but I don't have access to one, and I couldn't find an appropriate emulator.

Any suggestions on how I might test this feature?
Would you prefer I submit a PR with the current implementation, or should I hold off for now?

**Comment by maccesch** [comment]
@hcandelaria That's great! Yes please open a PR with what you have. We're going to find a way to test it somehow 👍🏼

**Comment by hcandelaria** [comment]
@maccesch Could you take a look at PR #155 and let me know if there is any feedback?
