### ISSUE TITLE
UseIntervalOptions fields are not public

### ISSUE THREAD

**Issue by MrAdhit** [Synphonyte/leptos-use#43]
Is this intentional?
If so, then how can we set the interval options when using `use_interval_with_options`?

https://github.com/Synphonyte/leptos-use/blob/7084b91c0abce11b3c0595a3a5272f2763e742b4/src/use_interval.rs#L92-L98

**Comment by MrAdhit** [comment]
Ah, it's a builder,
I completely didn't think of that because `use_interval_fn` which uses `UseIntervalFnOptions` has the fields set to public

**Comment by maccesch** [comment]
Yes that is an implementation detail unfortunately. I think I have to set them to `pub(crate)` or sth.

You're correct it's meant to be used as a builder pattern.

```rust
use_interval_with_options(
    ..., 
    UseIntervalOptions::default().immedate(false)
);
```
