### ISSUE TITLE
"Attempted to get a signal after it was disposed" in use_scroll

### ISSUE THREAD

**Issue by luxalpa** [Synphonyte/leptos-use#51]
The code for the `on_scroll_end` handler in `use_scroll_with_options` is debounced. This can cause the event handler to be run after the scope that it is in has already been disposed, resulting in this panic:

```
panicked at 'Attempted to get a signal after it was disposed.
signal created here: C:\Users\Luxalpa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos-use-0.8.2\src\use_scroll.rs:202:44
warning happened here: C:\Users\Luxalpa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos-use-0.8.2\src\use_scroll.rs:260:34', C:\Users\Luxalpa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos-use-0.8.2\src\use_scroll.rs:260:34
```

I think it needs to use and handle the result from `try_get_untracked` instead on this line:

https://github.com/Synphonyte/leptos-use/blob/28ab799156c4c3b7b93d8df20b9b1f067b68e364/src/use_scroll.rs#L260

**Comment by maccesch** [comment]
Thanks for reporting and diagnosing it so tightly
