### ISSUE TITLE
`use_local_storage` Not Storing Values as Expected

### ISSUE THREAD

**Issue by hongyilyu** [Synphonyte/leptos-use#62]
### Describe the bug
I'm experiencing an issue with `use_local_storage`. It appears that values are not being stored or retrieved correctly.

### Reproduce
1. `cargo leptos new --git https://github.com/leptos-rs/start-axum`
2. Add `leptos-use` to `Cargo.toml`
  * `leptos-use = {version = "0.9.0", features = ["ssr"]}`
3. Replace `app.rs` with
```Rust
use crate::error_template::{AppError, ErrorTemplate};
use leptos::*;
use leptos_meta::*;
use leptos_router::*;
use leptos_use::storage::{use_local_storage, StringCodec};

#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/repro.css"/>

        // sets the document title
        <Title text="Welcome to Leptos"/>

        // content for this welcome page
        <Router fallback=|| {
            let mut outside_errors = Errors::default();
            outside_errors.insert_with_default_key(AppError::NotFound);
            view! { <ErrorTemplate outside_errors/> }.into_view()
        }>
            <main>
                <Routes>
                    <Route path="" view=Demo/>
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn Demo() -> impl IntoView {
    let (state2, set_state2, _) = use_local_storage::<i32, StringCodec>("abc");

    view! {
        <button on:click=move |_| set_state2(state2.get() +1)>"State 2"</button>

        <p>
            "Second " <b>
                <code>"use_storage"</code>
            </b> ":"
        </p>

        <pre>{move || format!("{:#?}", state2.get())}</pre>
    }
}

```

### Expected behavior
I expect the local storage to update with the new value when it's set through the use_local_storage hook.

### Actual Behavior
No entry in local storage.
When refresh page, counter reset to zero.

### Environment:

    Browser: Tried with Firefox and Safari
    OS: macOS 14.2.1

**Comment by maccesch** [comment]
This is probably a duplicate #49 
Thanks for the excellent bug report!

**Comment by maccesch** [comment]
Weirdly enough it seems to work for me now although I definitely had a similar problem in the past.

@hongyilyu Could you confirm on your end?

**Comment by SGauvin** [comment]
@maccesch This doesn't work on my end using 0.9.0. I tried to use it on the latest commit but `leptos-use` doesn't compile :(

**Comment by maccesch** [comment]
@hongyilyu @SGauvin  I added `use_local_storage` to the `ssr` example in latest `main`. Could you try and run it and see if that works for you?

**Comment by hongyilyu** [comment]
@maccesch thanks for checking on this.
However the code above still does not work in `0.10`, I'm not sure if that's my problem.
I changed the sample code above to use `FromToStringCodec` and local browser still unable to store the value.

**Comment by maccesch** [comment]
I think I know why it's not working for you. 

You cannot enable the feature ssr permanently. Please check the docs or the SSR example of how to do it.
