### ISSUE TITLE
Docs: `WASM_BINDGEN_WEAKREF` should be enabled

### ISSUE THREAD

**Issue by maccesch** [Synphonyte/leptos-use#67]
Please see here https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/closure/struct.Closure.html#method.into_js_value

This is used in `use_event_listener` and other places throughout this lib.

**Comment by luxalpa** [comment]
This seems to be resolved in wasm-bindgen v0.2.91. 

https://github.com/rustwasm/wasm-bindgen/issues/3384

**Comment by maccesch** [comment]
Noice 👍🏼. I love stuff that fixes itself
