### ISSUE TITLE
trait not implemented

### ISSUE THREAD

**Issue by j00p34** [Synphonyte/leptos-use#81]
O'm trying to use use_element_visibility:

    let element = create_node_ref::<Div>();

    let is_visible = use_element_visibility(element);

But I get the following error:

error[E0277]: the trait bound `leptos::web_sys::Element: From<NodeRef<leptos::html::Div>>` is not satisfied
  --> src/app.rs:28:45
   |
28 |     let is_visible = use_element_visibility(element);
   |                      ---------------------- ^^^^^^^ the trait `From<NodeRef<leptos::html::Div>>` is not implemented for `leptos::web_sys::Element`
   |                      |
   |                      required by a bound introduced by this call
   |
   = help: the following other types implement trait `From<T>`:
             <leptos::web_sys::Element as From<JsValue>>
             <leptos::web_sys::Element as From<HtmlAnchorElement>>
             <leptos::web_sys::Element as From<HtmlAreaElement>>
             <leptos::web_sys::Element as From<HtmlAudioElement>>
             <leptos::web_sys::Element as From<HtmlBaseElement>>
             <leptos::web_sys::Element as From<HtmlBodyElement>>
             <leptos::web_sys::Element as From<HtmlBrElement>>
             <leptos::web_sys::Element as From<HtmlButtonElement>>
           and 59 others
   = note: required for `NodeRef<leptos::html::Div>` to implement `Into<leptos::web_sys::Element>`
   = note: required for `ElementMaybeSignal<NodeRef<leptos::html::Div>, leptos::web_sys::Element>` to implement `From<NodeRef<leptos::html::Div>>`
   = note: 1 redundant requirement hidden
   = note: required for `NodeRef<leptos::html::Div>` to implement `Into<ElementMaybeSignal<NodeRef<leptos::html::Div>, leptos::web_sys::Element>>`
note: required by a bound in `use_element_visibility`
  --> /home/timothy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.10.2/src/use_element_visibility.rs:46:9
   |
44 | pub fn use_element_visibility<El, T>(target: El) -> Signal<bool>
   |        ---------------------- required by a bound in this function
45 | where
46 |     El: Into<ElementMaybeSignal<T, web_sys::Element>>,
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `use_element_visibility`

**Comment by maccesch** [comment]
This looks like you have a Leptos version mismatch somewhere. What version of leptos-use do you use and what version of leptos?

**Comment by j00p34** [comment]
leptos-use = "0.10.2"
leptos-0.6.5

That should work together shouldn't it?
I'm trying to add it to the tailwind_axum example

**Comment by maccesch** [comment]
It should. Maybe try deleting your Cargo.lock and rebuild

**Comment by j00p34** [comment]
Doesn't make a difference, I've uploaded the code here https://github.com/j00p34/tailwind_axum 
Maybe you can have a look?

**Comment by maccesch** [comment]
Hehe your code is not like you wrote in the error message. Try to change it to exactly that and it works

**Comment by j00p34** [comment]
Yes, you're right thank's a lot. I've been messing around with it to fix that error. But in the code I was using previously I used leptos from a release I downloaded, where cargo was pointing to the local filesystem. I changed that to crates from the internet and I guess that fixed the problem. But I introduced a new error by my messing around. Well thank's a lot again, really appreciate your help.
