### ISSUE TITLE
Infinite scroll disposed error

### ISSUE THREAD

**Issue by zakstucke** [Synphonyte/leptos-use#98]
```
[Signal::update] At Location { file: "/Users/zak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.10.7/src/use_infinite_scroll.rs", line: 171, col: 37 }, you’re trying to update a Signal<bool> (defined at /Users/zak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.10.7/src/use_infinite_scroll.rs:108:37) that has already been disposed of. This is probably a logic error in a component that creates and disposes of scopes. If it does not cause any issues, it is safe to ignore this warning, which occurs only in debug mode.
```

Looks like some signals in `spawn_local` can happen after the component unmounts causing disposed of panics.
Can we switch to `try_` variants instead to avoid?

**Comment by maccesch** [comment]
Thanks for reporting!

Would you mind sharing code to reproduce this?

**Comment by zakstucke** [comment]
It might be tough to get a simple repro, I've found it in 2 cases in my project:
- Modals when they're shutting (where using this inside somewhere)
- Collapsible blocks (where using this inside somewhere)

It happens pretty randomly, but looking at the source it seems like it's probably the signal usage in `spawn_local` blocks that might need changing to `try` variants
